### PR TITLE
Migration to RC5, Forms 0.3.0

### PR DESCRIPTION
**Pull request by ciesielskico**
You've got a weird .gitignore file so I will describe the most important changes:

Followed the RC4->RC5 migration guide:

- updated dependencies in package.json
- added app.module.ts
- added NKDatetimeModule to the bottom of class src/ng2-datetime
- imported NKDatetimeModule into app.module
- removed NKDatetime and Datepipe from directives and pipes array
- commented out parts of template, app.component.html (the {{ and }} have to be HTML escaped, did'nt have the time for that)

### CODE REVIEW

**Comment by LbISS** [comment]
@nkalinov Could you please merge that PR? Many projets already migrated to RC6. :)

**Comment by DominicSachs** [comment]
+1

**Comment by nkalinov** [comment]
Sorry, was on holiday.
Thanks for the PR @ciesielskico! Will bump the version shortly...

**Comment by chocapic54** [comment]
thanks @ciesielskico ! and @nkalinov  to publish it on npm.

**Pull request merged**
